apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks1-27f3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks1-27f3"
  template:
    metadata:
      labels:
        app: "myaks1-27f3"
    spec:
      containers:
        - name: "myaks1-27f3"
          image: "mycrdemo1.azurecr.io/myaks1"
          ports:
          - containerPort: 8080